# Introducción {-}

Los avances en tecnologías de alto rendimiento están permitiendo la identificación simultánea de un gran número de clasificadores para ayudar en la toma de decisiones de procesos relevantes. Las curvas de características operativas de receptor (ROC), y especialmente el área bajo las curvas ROC (AUC), son herramientas útiles para evaluar y comparar el rendimiento de estos clasificadores en aplicaciones biomédicas y bioinformáticas.

De esta forma, se puede describir su utilidad para evaluar procesos discriminatorios, e.g. clasificando enfermedades con biomarcadores y paneles de expresión, seleccionando genes diferencialemente expresados en experimentos, etcétera. Es más, actualmente se han desarrollado diversos paquetes de software estadístico que facilitan el análisis utilizando estas curvas ROC.

Sin embargo, cuando una tarea requiere de una determinada precisión, el AUC no es un índice significativo del rendimiento del clasificador. Nuevas herramientas analíticas han sido propuestas y ampliamente usadas en investigación bajo rangos preestablecidos de especificidad, sin embargo hasta ahora los métodos basados basados en curvas ROC no han sido sensibles cuando existen puntos que se cruzan en varias curvas.

El objetivo de este trabajo es estudiar índices de áreas parciales los cuales permiten comparar porciones de estas curvas ROC, y su utilidad en apliaciones biomédicas y bioinformáticas.

## Estructura {-}

## Software y convenciones {-}

## Conjuntos de datos {-}
